buildroot: cca: Create a macvtap interface
So that VMMs like cloud-hypervisor can connect the guest to the host
network, create a macvtap interface at boot.

Recycle the buildroot overlay folder which doesn't seem to be used
anymore.

Signed-off-by: Jean-Philippe Brucker <jean-philippe@linaro.org>
Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>

diff --git a/br-ext/board/qemu/overlay/etc/init.d/S60macvtap b/br-ext/board/qemu/overlay/etc/init.d/S60macvtap
--- a/br-ext/board/qemu/overlay/etc/init.d/S60macvtap
+++ b/br-ext/board/qemu/overlay/etc/init.d/S60macvtap
@@ -1,13 +1,15 @@
 #!/bin/sh
 case "$1" in
   start)
-	printf "Starting network (udhcpc): "
-	udhcpc >> /var/log/udhcpc.log 2>&1
+	printf "Setting up macvtap... "
+	ip link add link eth0 name macvtap0 type macvtap
+	[ $? != 0 ] && echo "FAIL" && exit 1
+	ip link set macvtap0 up
 	[ $? = 0 ] && echo "OK" || echo "FAIL"
 	;;
   stop)
-	printf "Stopping network (udhcpc): "
-	killall udhcpc
+	printf "Destroying macvtap... "
+	ip link del macvtap0
 	[ $? = 0 ] && echo "OK" || echo "FAIL"
 	;;
   restart|reload)
@@ -20,4 +22,3 @@ case "$1" in
 esac
 
 exit $?
-
